workarounds=["bitvec", "rustls", "chrono", "rustix"]
accepted=[
    "Apache-2.0",
    "MIT",
    "ISC",
    "MPL-2.0",
    "BSD-3-Clause",
    "Unicode-DFS-2016",
    "Unicode-3.0",
    "OpenSSL",
    "Zlib",
    "CDLA-Permissive-2.0",
]
targets=["x86_64-unknown-linux-musl", "aarch64-unknown-linux-musl", "aarch64-apple-darwin"]
ignore-build-dependencies=true
ignore-dev-dependencies=true
filter-noassertion=true
